data_path: C:\Users\AdminCOOP\Desktop\Energy_consumption_Prediction\Model_improved\sg_roads
           

use_loopup: True


start_hour: 8

end_hour: 20

time_window: 60 


use_externel: False

use_matrix_fuse: True

observe_length: 12

predict_length: 1


observe_p: 7   #in the day, we observe the 7 first values 

observe_t: 2

test_ratio: 0.25

model_name: RESNET_BILSTM

model_path: C:\Users\AdminCOOP\Desktop\Prediction_of_Energy_consumption\Model\model

use_cache_model: False

epochs: 40

batch_size: 1

early_stopping: 2500

learning_rate: 0.001


